export const SUBMIT_FOR_UPDATE_EC = "SUBMIT_FOR_UPDATE_EC";
export const SUBMIT_FOR_UPDATE_ISSUE = "SUBMIT_FOR_UPDATE_ISSUE";
export const EMPTY_EC = "EMPTY_EC";
export const EMPTY_ISSUE = "EMPTY_ISSUE";
